"""Audited session moderation and participant recourse, disposable metadata only."""
import argparse,datetime,json,pathlib,subprocess,time,uuid
p=argparse.ArgumentParser();p.add_argument('--root',required=True);p.add_argument('--base',required=True);p.add_argument('--cli',required=True)
a=p.parse_args();root=pathlib.Path(a.root).resolve()
if root.parent!=pathlib.Path('/var/tmp') or not root.name.startswith('fans-admission-wp-'):raise RuntimeError('Disposable root required')
wp=root/'wordpress';worker=wp/'wp-content/plugins/faluss-platform/tests/Fans/Hof/recipe/worker.php';fixture=json.loads((root/'session.json').read_text());profiles=fixture['profiles']
actors={name:value['id'] for name,value in fixture['sessions'].items()};actors['guest']=0;checks=[]
def start(actor,action,**values):
    path=root/(str(uuid.uuid4())+'.json');path.write_text(json.dumps(dict(actor=actors[actor],action=action,**values)));path.chmod(0o600)
    return subprocess.Popen(['php',a.cli,'--allow-root','--path='+str(wp),'eval-file',str(worker),str(path),'--use-include'],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
def finish(process):
    out,err=process.communicate(timeout=30)
    if process.returncode:raise RuntimeError('Private moderation worker failed: '+err[-1200:])
    return json.loads(out)
def call(actor,action,**values):return finish(start(actor,action,**values))
def data(actor,action,**values):
    result=call(actor,action,**values)
    if 'error' in result:raise AssertionError(action+': '+result['error'])
    return result['data']
def check(name,condition):
    if not condition:raise AssertionError(name)
    checks.append(name);print('PASS '+name,flush=True)
def sql(query):
    result=subprocess.run(['mariadb','--no-defaults','--socket='+str(root/'sql.sock'),'-uroot','--batch','--skip-column-names','admission_recipe','-e',query],capture_output=True,text=True)
    if result.returncode:raise RuntimeError('Private moderation SQL failed')
    return result.stdout.strip()
def parallel(requests):
    barrier=root/('barrier-'+str(uuid.uuid4()));processes=[start(actor,action,**dict(values,barrier=str(barrier),worker=i)) for i,(actor,action,values) in enumerate(requests)]
    deadline=time.monotonic()+15
    while not all(pathlib.Path(str(barrier)+'.'+str(i)+'.ready').exists() for i in range(len(processes))):
        if time.monotonic()>deadline:raise RuntimeError('Concurrent moderation workers timed out')
        time.sleep(.02)
    pathlib.Path(str(barrier)+'.go').touch();return [finish(process) for process in processes]
now=datetime.datetime.now(datetime.timezone.utc)
rules=dict(title='Recette session — lumière',rules_text='Critères de participation fictifs examinés, sans achat ou récompense.',category='arts',scope='international',country='',territory_ref='',timezone='Europe/Paris',starts_at=(now+datetime.timedelta(hours=1)).strftime('%Y-%m-%d %H:%M:%S.%f'),ends_at=(now+datetime.timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S.%f'))
check('Normal activation creates no session review schema',sql("SHOW TABLES LIKE 'wp_fans_hof_review_schema'")=='')
data('admin','install');data('admin','session_install')
check('Ordinary members cannot install review schema',call('member','review_install')['error']=='hof_forbidden')
data('admin','review_install');check('Explicit review schema installation is idempotent',data('admin','review_install')['ready'])
for actor in ['member','other','waiting']:
    data('admin','admit',creator=profiles[actor],status='active');data(actor,'editorial_submit',revision=0);data('admin','editorial_decide',creator=profiles[actor],revision=1,decision='approve',reason='allowed_editorial')
session=data('member','session_create',rules=rules);sid=session['session_id']
check('Profile approval does not approve session rules',call('member','session_open',session=sid,revision=1)['error']=='hof_session_approval_required')
check('Foreign creator cannot submit another session',call('other','review_submit',session=sid,session_revision=1,revision=0)['error']=='hof_session_forbidden')
submitted=data('member','review_submit',session=sid,session_revision=1,revision=0)
check('Submitted session content remains pending',submitted['state']=='pending')
check('Creator cannot approve their own rules',call('member','review_decide',session=sid,revision=1,decision='approve',reason='allowed_session')['error']=='hof_forbidden')
check('Foreign creator cannot read private review or history',call('other','review_own',session=sid)['error']=='hof_session_forbidden' and call('other','review_history',session=sid)['error']=='hof_session_forbidden')
results=parallel([('admin','review_decide',dict(session=sid,revision=1,decision='approve',reason='allowed_session')),('admin','review_decide',dict(session=sid,revision=1,decision='reject',reason='needs_revision'))])
check('Concurrent moderation commits one decision only',sum('data' in r for r in results)==1 and sum(r.get('error')=='hof_review_revision_conflict' for r in results)==1)
review=data('member','review_own',session=sid)
if review['state']=='approved':
    review=data('admin','review_decide',session=sid,revision=int(review['revision']),decision='revoke',reason='needs_revision')
review=data('member','review_appeal',session=sid,revision=int(review['revision']),explanation='Recours fictif sur ces règles exactes.')
check('Session appeal is not an approval',review['state']=='appealed')
review=data('admin','review_decide',session=sid,revision=int(review['revision']),decision='approve',reason='allowed_session')
edited=data('member','session_edit',session=sid,revision=1,rules=dict(rules,title='Nouvelle lumière'))
check('Edited rules cannot reuse a previous approval',call('member','session_open',session=sid,revision=2)['error']=='hof_session_approval_required')
history=data('member','review_history',session=sid)
check('Private versioned history preserves exact prior editorial rules',json.loads(history[0]['rules_json'])['title']==rules['title'] and all('actor_id' not in event for event in history))
review=data('member','review_submit',session=sid,session_revision=2,revision=int(review['revision']))
data('member','session_edit',session=sid,revision=2,rules=dict(rules,title='Troisième lumière'))
check('A moderator cannot approve content edited since submission',call('admin','review_decide',session=sid,revision=int(review['revision']),decision='approve',reason='allowed_session')['error']=='hof_review_rules_changed')
review=data('member','review_submit',session=sid,session_revision=3,revision=int(review['revision']))
review=data('admin','review_decide',session=sid,revision=int(review['revision']),decision='approve',reason='allowed_session')
opened=data('member','session_open',session=sid,revision=3)
check('Approved current rules freeze while opening still awaits Hub proof',opened['state']=='opening' and opened['frozen_sha256']==review['rules_sha256'])
data('waiting','session_apply',session=sid,revision=4,digest=opened['frozen_sha256']);data('member','session_admit',session=sid,revision=5,creator=profiles['waiting'],allow=False)
check('Another creator cannot appeal a candidate refusal',call('other','participation_appeal',session=sid,role_revision=2,explanation='Foreign appeal')['error']=='hof_appeal_refusal_required')
case=data('waiting','participation_appeal',session=sid,role_revision=2,explanation='Recours fictif personnel, critères à réexaminer.')
check('Participant recourse is pending and not an admission',case['state']=='pending' and data('waiting','session_inspect',session=sid)['roles'][0]['state']=='refused')
check('Duplicate recourse for the same decision is refused',call('waiting','participation_appeal',session=sid,role_revision=2,explanation='Duplicate')['error']=='hof_appeal_already_submitted')
check('Session organizer cannot read another participant private recourse',call('member','appeal_own',case=case['case_id'])['error']=='hof_appeal_forbidden')
check('Owner queue has no recipient override',data('other','appeal_list')==[] and len(data('waiting','appeal_list'))==1)
check('Only the moderator can decide a participant appeal',call('member','appeal_decide',case=case['case_id'],revision=1,decision='admit',reason='criteria_satisfied')['error']=='hof_forbidden')
results=parallel([('admin','appeal_decide',dict(case=case['case_id'],revision=1,decision='uphold',reason='needs_revision'))]*2)
check('Concurrent recourse decisions commit one case revision',sum('data' in r for r in results)==1 and sum(r.get('error')=='hof_appeal_revision_conflict' for r in results)==1)
data('waiting','session_apply',session=sid,revision=6,digest=opened['frozen_sha256']);data('member','session_admit',session=sid,revision=7,creator=profiles['waiting'],allow=False)
newcase=data('waiting','participation_appeal',session=sid,role_revision=4,explanation='Nouvelle décision, précisions fictives apportées.')
before=sql('SELECT UTC_TIMESTAMP(6)');data('admin','appeal_decide',case=newcase['case_id'],revision=1,decision='admit',reason='criteria_satisfied')
role=data('waiting','session_inspect',session=sid)['roles'][0]
check('Favourable moderator recourse admits only future contributions',role['state']=='admitted' and role['admitted_at']>=before and role['rules_sha256']==opened['frozen_sha256'])
check('Prior appeal remains available without rewriting its decision',data('waiting','appeal_own',case=case['case_id'])['result']=='uphold')
data('other','session_apply',session=sid,revision=9,digest=opened['frozen_sha256']);data('member','session_admit',session=sid,revision=10,creator=profiles['other'],allow=False)
closedcase=data('other','participation_appeal',session=sid,role_revision=2,explanation='Recours avant fermeture de contexte.')
review=data('admin','review_decide',session=sid,revision=int(review['revision']),decision='revoke',reason='prohibited_content')
current=data('member','session_inspect',session=sid)['session']
check('Moderation revocation stops choices and awaits effective close proof',current['state']=='closing' and current['closure_action']=='suspended')
check('Closing is not sufficient for readmission',call('member','session_readmission',session=sid,revision=int(current['revision']))['error']=='hof_readmission_not_available')
check('Participant recourse cannot reopen a closed context',call('admin','appeal_decide',case=closedcase['case_id'],revision=1,decision='admit',reason='criteria_satisfied')['error']=='hof_invalid_session_transition')
check('Closed recourse can be reasoned without inventing an admission',data('admin','appeal_decide',case=closedcase['case_id'],revision=1,decision='close_without_admission',reason='context_closed')['result']=='close_without_admission')
rollback=data('member','session_create',rules=dict(rules,title='Recette annulation atomique'))
sql("CREATE TRIGGER review_audit_failure BEFORE INSERT ON wp_fans_hof_review_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Controlled review failure'")
check('Review and exact snapshot roll back when journal fails','error' in call('member','review_submit',session=rollback['session_id'],session_revision=1,revision=0) and data('member','review_own',session=rollback['session_id']) is None)
sql('DROP TRIGGER review_audit_failure')
data('member','fixture_approve_session',session=rollback['session_id']);other_open=data('member','session_open',session=rollback['session_id'],revision=1)
data('waiting','session_apply',session=rollback['session_id'],revision=2,digest=other_open['frozen_sha256']);data('member','session_admit',session=rollback['session_id'],revision=3,creator=profiles['waiting'],allow=False)
failedcase=data('waiting','participation_appeal',session=rollback['session_id'],role_revision=2,explanation='Recours fictif, test de transaction indivisible.')
sql("CREATE TRIGGER appeal_audit_failure BEFORE INSERT ON wp_fans_hof_review_appeal_log FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Controlled appeal failure'")
check('Case, admission and session journal roll back together on appeal audit failure','error' in call('admin','appeal_decide',case=failedcase['case_id'],revision=1,decision='admit',reason='criteria_satisfied') and data('waiting','appeal_own',case=failedcase['case_id'])['state']=='pending' and data('waiting','session_inspect',session=rollback['session_id'])['roles'][0]['state']=='refused' and data('member','session_inspect',session=rollback['session_id'])['session']['revision']=='4')
sql('DROP TRIGGER appeal_audit_failure');data('admin','appeal_decide',case=failedcase['case_id'],revision=1,decision='admit',reason='criteria_satisfied')
check('Retry after rolled back audit commits one future admission',data('waiting','appeal_own',case=failedcase['case_id'])['revision']=='2')
# State precondition injection only. This is deliberately not presented as an attested Hub close.
sql("UPDATE wp_fans_hof_session_records SET state='suspended' WHERE session_id='"+sid+"'")
review=data('member','review_appeal',session=sid,revision=int(review['revision']),explanation='Recours fictif pour réadmission après suspension effective injectée.')
data('admin','review_decide',session=sid,revision=int(review['revision']),decision='approve',reason='allowed_session')
resumed=data('member','session_readmission',session=sid,revision=int(current['revision']))
check('Injected effective suspension allows versioned metadata readmission only',resumed['state']=='opening' and resumed['barrier_version']=='2' and resumed['frozen_sha256']==opened['frozen_sha256'])
cancelled=data('member','session_create',rules=dict(rules,title='Session annulée de recette'));data('member','session_close',session=cancelled['session_id'],revision=1,state='cancelled')
check('Cancellation cannot be transformed into readmission',call('member','session_readmission',session=cancelled['session_id'],revision=2)['error']=='hof_readmission_not_available')
check('Every review revision has one exact private historical snapshot',sql('SELECT COUNT(*) FROM wp_fans_hof_review_sessions r WHERE r.revision<>(SELECT COUNT(*) FROM wp_fans_hof_review_events e WHERE e.session_id=r.session_id)')=='0')
check('Every appeal revision has one durable decision event',sql('SELECT COUNT(*) FROM wp_fans_hof_review_appeals r WHERE r.revision<>(SELECT COUNT(*) FROM wp_fans_hof_review_appeal_log e WHERE e.case_id=r.case_id)')=='0')
check('Editorial guard refuses use outside an existing transaction',not data('admin','editorial_guard_outside',creator=profiles['other']))
guard=root/('editorial-guard-'+str(uuid.uuid4()))
held=start('admin','editorial_guard_hold',creator=profiles['other'],guard=str(guard))
deadline=time.monotonic()+15
while not pathlib.Path(str(guard)+'.ready').exists():
    if time.monotonic()>deadline:raise RuntimeError('Editorial guard did not acquire its lock')
    time.sleep(.02)
revoker=start('admin','editorial_decide',creator=profiles['other'],revision=2,decision='revoke',reason='needs_revision')
try:
    time.sleep(.5)
    check('Concurrent editorial withdrawal waits for the admission transaction',revoker.poll() is None)
finally:pathlib.Path(str(guard)+'.release').touch()
check('Editorial guard preserves the caller transaction until release',finish(held)['data']==dict(approved=True,in_transaction=True))
revoked=finish(revoker)
if 'error' in revoked:raise AssertionError('Concurrent editorial decision: '+revoked['error'])
check('Withdrawal commits after release and prevents subsequent admission',revoked['data']['state']=='rejected' and call('member','session_invite',session=rollback['session_id'],revision=5,creator=profiles['other'])['error']=='hof_approved_creator_required')
sql('ALTER TABLE wp_fans_hof_review_events ENGINE=MyISAM')
check('Divergent review storage fails closed','error' in call('member','review_own',session=sid));sql('ALTER TABLE wp_fans_hof_review_events ENGINE=InnoDB')
check('No score or economic operation is exposed by moderation',sql("SHOW TABLES LIKE '%pf_ledger'")=='' and sql("SHOW TABLES LIKE 'wp_fans_hof_scores'")=='')
(root/'checks.json').write_text(json.dumps(dict(scope='B2 session moderation on disposable WordPress/MariaDB; seeded local SSO links, injected suspension precondition not Hub proof, no economic opening',count=len(checks),checks=checks),indent=2))
