"""Principal activity examinations on disposable WordPress/MariaDB, fictitious criteria only."""
import argparse,datetime,json,pathlib,subprocess,time,uuid
p=argparse.ArgumentParser()
p.add_argument('--root',required=True);p.add_argument('--base',required=True);p.add_argument('--cli',required=True)
a=p.parse_args();root=pathlib.Path(a.root).resolve()
if root.parent!=pathlib.Path('/var/tmp') or not root.name.startswith('fans-admission-wp-'):raise RuntimeError('Disposable root required')
wp=root/'wordpress';worker=wp/'wp-content/plugins/faluss-platform/tests/Fans/Hof/recipe/worker.php'
fixture=json.loads((root/'session.json').read_text());profiles=fixture['profiles']
actors={name:value['id'] for name,value in fixture['sessions'].items()};actors['guest']=0;checks=[]
def start(actor,action,**values):
    path=root/(str(uuid.uuid4())+'.json');path.write_text(json.dumps(dict(actor=actors[actor],action=action,**values)));path.chmod(0o600)
    return subprocess.Popen(['php',a.cli,'--allow-root','--path='+str(wp),'eval-file',str(worker),str(path),'--use-include'],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
def finish(process):
    out,err=process.communicate(timeout=30)
    if process.returncode:raise RuntimeError('Private territory worker failed: '+err[-1200:])
    return json.loads(out)
def call(actor,action,**values):return finish(start(actor,action,**values))
def data(actor,action,**values):
    result=call(actor,action,**values)
    if 'error' in result:raise AssertionError(action+': '+result['error'])
    return result['data']
def check(name,condition):
    if not condition:raise AssertionError(name)
    checks.append(name);print('PASS '+name,flush=True)
def sql(query):
    result=subprocess.run(['mariadb','--no-defaults','--socket='+str(root/'sql.sock'),'-uroot','--batch','--skip-column-names','admission_recipe','-e',query],capture_output=True,text=True)
    if result.returncode:raise RuntimeError('Private territory SQL failed')
    return result.stdout.strip()
def parallel(requests):
    barrier=root/('barrier-'+str(uuid.uuid4()));processes=[start(actor,action,**dict(values,barrier=str(barrier),worker=i)) for i,(actor,action,values) in enumerate(requests)]
    deadline=time.monotonic()+15
    while not all(pathlib.Path(str(barrier)+'.'+str(i)+'.ready').exists() for i in range(len(processes))):
        if time.monotonic()>deadline:raise RuntimeError('Concurrent territory workers timed out')
        time.sleep(.02)
    pathlib.Path(str(barrier)+'.go').touch();return [finish(process) for process in processes]

now=datetime.datetime.now(datetime.timezone.utc)
rules=dict(title='Recette territoriale fictive',rules_text='Participation volontaire, territoires examinés selon les critères de recette.',category='arts',scope='local',country='FR',territory_ref='fixture.fr-a',timezone='Europe/Paris',starts_at=(now+datetime.timedelta(hours=1)).strftime('%Y-%m-%d %H:%M:%S.%f'),ends_at=(now+datetime.timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S.%f'))
policy=str(uuid.uuid4());policy2=str(uuid.uuid4())
criteria=dict(criteria_url='https://policy.example.test/fictitious',criteria_text='Critères fictifs ; ne valent pas admission de production.',countries=['FR','BE'],territories={'fixture.fr-a':dict(country='FR',name='Territoire fictif A'),'fixture.fr-b':dict(country='FR',name='Territoire fictif B'),'fixture.be':dict(country='BE',name='Territoire fictif belge')})
check('Normal activation creates no territorial schema or default policy',sql("SHOW TABLES LIKE 'wp_fans_hof_territory_schema'")=='')
data('admin','install');data('admin','session_install')
check('Members cannot install territory schema',call('member','territory_install')['error']=='hof_forbidden')
data('admin','territory_install')
check('Territory installation is explicit and idempotent',data('admin','territory_install')['ready'])
check('No criteria or countries are silently created',sql('SELECT COUNT(*) FROM wp_fans_hof_territory_policies')=='0')
check('Members cannot publish their own examination criteria',call('member','territory_policy',policy=policy,rules=criteria)['error']=='hof_forbidden')
registered=data('admin','territory_policy',policy=policy,rules=criteria)
check('French criteria and named localities are persisted exactly',registered['criteria_text']==criteria['criteria_text'] and len(registered['policy_sha256'])==64)
check('Replaying an identical policy keeps one immutable version',data('admin','territory_policy',policy=policy,rules=criteria)==registered)
check('Changing registered criteria requires a new explicit version',call('admin','territory_policy',policy=policy,rules=dict(criteria,criteria_text='Different criteria'))['error']=='hof_territory_policy_immutable')
for actor in ['guest','unlinked','admin']:
    check('Private declaration refuses '+actor,'error' in call(actor,'territory_own'))
for actor in ['member','other','waiting']:
    data('admin','admit',creator=profiles[actor],status='active');data(actor,'editorial_submit',revision=0)
    data('admin','editorial_decide',creator=profiles[actor],revision=1,decision='approve',reason='allowed_editorial')
check('Approved public presentation does not certify a principal territory',data('member','territory_own')['state']=='absent')
check('Unknown locality is not inferred from a country',call('member','territory_submit',policy=policy,country='FR',territory='unknown',revision=0)['error']=='hof_unknown_principal_territory')
check('Locality in a different country is refused',call('member','territory_submit',policy=policy,country='FR',territory='fixture.be',revision=0)['error']=='hof_unknown_principal_territory')
submitted=data('member','territory_submit',policy=policy,country='FR',territory='fixture.fr-a',revision=0)
check('Declaration remains pending without any approval',submitted['state']=='pending' and submitted['approved_revision']=='0')
local=data('member','session_create',rules=rules)
check('Pending territory cannot open a local session',call('member','session_open',session=local['session_id'],revision=1,policy=policy)['error']=='hof_reviewed_territory_required')
check('A failed opening leaves no policy binding or session revision',sql("SELECT COUNT(*) FROM wp_fans_hof_territory_bindings WHERE session_id='"+local['session_id']+"'")=='0' and data('member','session_inspect',session=local['session_id'])['session']['revision']=='1')
check('Creator cannot approve their own territorial declaration',call('member','territory_decide',creator=profiles['member'],revision=1,decision='approve',reason='criteria_satisfied')['error']=='hof_forbidden')
results=parallel([('admin','territory_decide',dict(creator=profiles['member'],revision=1,decision='approve',reason='criteria_satisfied')),('admin','territory_decide',dict(creator=profiles['member'],revision=1,decision='reject',reason='needs_revision'))])
check('Concurrent decisions commit one revision and reject the other',sum('data' in r for r in results)==1 and sum(r.get('error')=='hof_territory_revision_conflict' for r in results)==1)
own=data('member','territory_own')
if own['state']=='rejected':
    own=data('member','territory_appeal',revision=int(own['revision']),explanation='Recours fictif, activité du territoire A.')
    own=data('admin','territory_decide',creator=profiles['member'],revision=int(own['revision']),decision='approve',reason='criteria_satisfied')
opened=data('member','session_open',session=local['session_id'],revision=1,policy=policy)
check('Reviewed matching local territory prepares opening without Hub acknowledgement',opened['state']=='opening')
check('Territorial policy version is frozen with the session',sql("SELECT policy_id FROM wp_fans_hof_territory_bindings WHERE session_id='"+local['session_id']+"'")==policy)
for actor,country,ref in [('other','FR','fixture.fr-b'),('waiting','BE','fixture.be')]:
    data(actor,'territory_submit',policy=policy,country=country,territory=ref,revision=0)
    data('admin','territory_decide',creator=profiles[actor],revision=1,decision='approve',reason='criteria_satisfied')
national=data('member','session_create',rules=dict(rules,scope='national',territory_ref=''))
data('member','session_invite',session=national['session_id'],revision=1,creator=profiles['other']);data('other','session_answer',session=national['session_id'],revision=2,accept=True)
check('National coorganization accepts different examined localities in the same country',data('member','session_open',session=national['session_id'],revision=3,policy=policy)['state']=='opening')
data('waiting','session_apply',session=local['session_id'],revision=2,digest=opened['frozen_sha256'])
check('Examined creator in another country is not admitted to local session',call('member','session_admit',session=local['session_id'],revision=3,creator=profiles['waiting'],allow=True)['error']=='hof_reviewed_territory_required')
data('member','session_admit',session=local['session_id'],revision=3,creator=profiles['waiting'],allow=False)
data('other','session_apply',session=local['session_id'],revision=4,digest=opened['frozen_sha256'])
check('Different examined localities are refused by a local session',call('member','session_admit',session=local['session_id'],revision=5,creator=profiles['other'],allow=True)['error']=='hof_reviewed_territory_required')
data('other','territory_submit',policy=policy,country='FR',territory='fixture.fr-a',revision=2)
check('A changed declaration suspends future territorial eligibility pending review',call('member','session_admit',session=local['session_id'],revision=5,creator=profiles['other'],allow=True)['error']=='hof_reviewed_territory_required')
data('admin','territory_decide',creator=profiles['other'],revision=3,decision='approve',reason='criteria_satisfied')
check('Reviewed matching participant is admitted only for future contributions',data('member','session_admit',session=local['session_id'],revision=5,creator=profiles['other'],allow=True)['revision']=='6')
data('admin','territory_decide',creator=profiles['other'],revision=4,decision='revoke',reason='territory_unsubstantiated')
check('Revocation retains a motivated private decision',data('other','territory_own')['state']=='rejected' and data('other','territory_own')['approved_revision']=='0')
appealed=data('other','territory_appeal',revision=5,explanation='Recours fictif sur la déclaration examinée.')
check('Private recourse does not silently readmit a creator',appealed['state']=='appealed' and appealed['approved_revision']=='0')
check('Members cannot read the moderator examination queue',call('member','territory_review')['error']=='hof_forbidden')
check('Only moderators receive recourse text in their bounded review',any(row['appeal_text']==appealed['appeal_text'] for row in data('admin','territory_review')))
data('admin','territory_decide',creator=profiles['other'],revision=6,decision='approve',reason='criteria_satisfied')
check('Reexamination versions the approval without replacing the frozen policy',data('other','territory_own')['approved_revision']=='7' and sql("SELECT policy_id FROM wp_fans_hof_territory_bindings WHERE session_id='"+local['session_id']+"'")==policy)
data('other','territory_withdraw',revision=7)
check('Owner withdrawal clears private current locality and future approval',data('other','territory_own')['country']=='' and data('other','territory_own')['approved_revision']=='0')
international=data('waiting','session_create',rules=dict(rules,scope='international',country='',territory_ref=''))
check('International session has no invented territorial restriction',data('waiting','session_open',session=international['session_id'],revision=1)['state']=='opening')
data('admin','territory_policy',policy=policy2,rules=dict(criteria,criteria_text='Nouvelle version fictive des critères.'))
check('New criteria never rewrite earlier frozen session policy',sql("SELECT policy_id FROM wp_fans_hof_territory_bindings WHERE session_id='"+local['session_id']+"'")==policy)
check('Internal binding refuses a caller outside the session transaction',call('admin','territory_bind_outside',session=local['session_id'],policy=policy)['error']=='hof_territory_transaction_required')
sql("UPDATE wp_fans_hof_territory_policies SET criteria_text='Corrupted fixture' WHERE policy_id='"+policy+"'")
check('Corrupted policy cannot be replayed as a valid immutable examination',call('admin','territory_policy',policy=policy,rules=criteria)['error']=='hof_territory_policy_corrupt')
sql("UPDATE wp_fans_hof_territory_policies SET criteria_text=0x"+criteria['criteria_text'].encode().hex()+" WHERE policy_id='"+policy+"'")
check('Restoring exact criteria preserves the frozen policy hash',data('admin','territory_policy',policy=policy,rules=criteria)['policy_sha256']==registered['policy_sha256'])
before=data('member','territory_own')
sql("CREATE TRIGGER territory_audit_failure BEFORE INSERT ON wp_fans_hof_territory_decisions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Controlled territory failure'")
check('Journal failure rolls back declaration and previous approval together','error' in call('member','territory_submit',policy=policy2,country='FR',territory='fixture.fr-b',revision=int(before['revision'])) and data('member','territory_own')==before)
sql('DROP TRIGGER territory_audit_failure')
check('Every territorial revision has one immutable journal decision',sql('SELECT COUNT(*) FROM wp_fans_hof_territory_creators c WHERE c.revision<>(SELECT COUNT(*) FROM wp_fans_hof_territory_decisions d WHERE d.creator_id=c.creator_id)')=='0')
sql('ALTER TABLE wp_fans_hof_territory_creators ENGINE=MyISAM')
check('Nontransactional territorial schema is refused','error' in call('member','territory_own'))
sql('ALTER TABLE wp_fans_hof_territory_creators ENGINE=InnoDB')
check('Compatible schema restoration preserves decisions',data('member','territory_own')==before)
check('No economic operation, default retention or public score is introduced',sql("SHOW TABLES LIKE '%pf_ledger'")=='' and sql("SHOW TABLES LIKE 'wp_fans_hof_scores'")=='')
(root/'checks.json').write_text(json.dumps(dict(scope='B2 territorial governance on disposable WordPress/MariaDB; fictitious public criteria, local SSO links only, no economic or production admission',count=len(checks),checks=checks),indent=2))
