const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const launchBrowser = require('./browser-engine.cjs');
const base = process.env.FANS_UI_BASE || 'http://127.0.0.1:8765';
const url = `${base}/app/creator/creer`;
const output = process.env.FANS_UI_OUTPUT || path.resolve(__dirname, '../../../../docs/evidence/fans-48h/lot-4');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await launchBrowser();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, javaScriptEnabled: false });
    const cookie = (name, value) => context.addCookies([{ name, value, url: base }]);
    await cookie('fans_ui_author', 'open');
    for (const role of ['guest', 'admin', 'fan']) {
      await cookie('fans_ui_role', role);
      assert.equal((await context.request.post(url, { form: { author_action: 'create', text: 'forbidden' } })).status(), role === 'fan' ? 404 : 403);
    }
    await cookie('fans_ui_role', 'creator');
    const page = await context.newPage();
    await page.goto(url);
    assert.equal(await page.locator('.fu-nav__item').count(), 8);
    const key = await page.locator('[name=creation_key]').inputValue();
    assert.match(key, /^[0-9a-f-]{36}$/);
    const create = { author_action: 'create', creation_key: key, fans_author_nonce: 'fixture-fans_author', text: 'Fixture de recette — texte privé à modérer.' };
    assert.equal((await context.request.post(url, { form: { ...create, fans_author_nonce: 'wrong' } })).status(), 403);
    await page.reload();
    await page.getByText('Aucun texte enregistré.', { exact: true }).waitFor();
    await page.getByLabel('Votre texte', { exact: true }).fill(create.text);
    const submittedKey = await page.locator('[name=creation_key]').inputValue();
    create.creation_key = submittedKey;
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(output, 'creation-desktop.png'), fullPage: true });
    await page.getByRole('button', { name: 'Soumettre à la modération', exact: true }).click();
    await page.getByText('Demande traitée. État actuel : En attente de modération.', { exact: true }).waitFor();
    assert.equal(await page.locator('.fu-author__item').count(), 1);
    assert.equal((await context.request.post(url, { form: create })).status(), 200);
    await page.getByRole('link', { name: 'Nouveau texte / relire la liste', exact: true }).click();
    assert.equal(await page.locator('.fu-author__item').count(), 1, 'same intention must not duplicate');
    await page.getByRole('link', { name: 'Ouvrir ce texte', exact: false }).click();
    const itemUrl = page.url();
    const editForm = page.locator('.fu-author__form');
    const id = await editForm.locator('[name=publication_id]').inputValue();
    const revision = await editForm.locator('[name=revision]').inputValue();
    assert.equal(revision, '1');
    await page.getByLabel('Modifier le texte', { exact: false }).fill('Fixture de recette — modification.');
    await page.getByRole('button', { name: 'Soumettre à la modération', exact: true }).click();
    await page.getByText('Demande traitée. État actuel : En attente de modération.', { exact: true }).waitFor();
    const stale = await context.request.post(itemUrl, { form: { fans_author_nonce: create.fans_author_nonce, author_action: 'edit', publication_id: id, revision, text: 'obsolete' } });
    assert.equal(stale.status(), 409);
    assert.doesNotMatch(await stale.text(), /Demande traitée/);
    const unconfirmed = await context.request.post(url, { form: { fans_author_nonce: create.fans_author_nonce, author_action: 'withdraw', publication_id: id, revision: '2' } });
    assert.equal(unconfirmed.status(), 400);
    await cookie('fans_ui_profile', 'suspended');
    await page.goto(itemUrl);
    assert.equal(await page.locator('.fu-author__form').count(), 0);
    await page.getByLabel('Je confirme le retrait', { exact: false }).check();
    await page.getByRole('button', { name: 'Retirer ce texte', exact: true }).click();
    await page.getByText('Demande traitée. État actuel : Retiré.', { exact: true }).waitFor();
    assert.doesNotMatch(await page.locator('.fu-author').innerText(), /Fixture de recette — modification/);
    await page.goto(`${url}?publication=123e4567-e89b-42d3-a456-426614174099`);
    await page.getByText('Ce texte est indisponible ou ne vous appartient pas.', { exact: true }).waitFor();
    await cookie('fans_ui_profile', 'active');
    await cookie('fans_ui_write_error', '503');
    await page.goto(url);
    const retryKey = await page.locator('[name=creation_key]').inputValue();
    await page.getByLabel('Votre texte', { exact: true }).fill('Fixture de recette — réessai identique.');
    await page.getByRole('button', { name: 'Soumettre à la modération', exact: true }).click();
    await page.getByRole('button', { name: 'Réessayer la même demande', exact: true }).waitFor();
    assert.equal(await page.locator('[name=creation_key]').inputValue(), retryKey);
    assert.equal(await page.locator('textarea').getAttribute('readonly'), '');
    await cookie('fans_ui_write_error', '');
    await page.getByRole('button', { name: 'Réessayer la même demande', exact: true }).click();
    await page.getByText('Demande traitée. État actuel : En attente de modération.', { exact: true }).waitFor();
    await cookie('fans_ui_write_error', '429');
    const quota = await context.request.post(url, { form: { ...create, creation_key: '123e4567-e89b-42d3-a456-426614174098' } });
    assert.equal(quota.status(), 429);
    assert.match(await quota.text(), /Limite de publication atteinte/);
    await cookie('fans_ui_write_error', '');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(url);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
    await page.evaluate(() => window.scrollTo(0, document.querySelector('#fu-author').offsetTop - 16));
    await page.screenshot({ path: path.join(output, 'creation-mobile.png') });
    await page.getByRole('link', { name: 'Ouvrir ce texte', exact: false }).last().click();
    await page.evaluate(() => window.scrollTo(0, document.querySelector('.fu-author__item').offsetTop - 16));
    await page.screenshot({ path: path.join(output, 'edition-mobile.png') });
    await cookie('fans_ui_author', 'closed');
    await page.goto(url);
    assert.equal(await page.locator('.fu-author form').count(), 0);
    await page.getByText('La création et la gestion des textes sont indisponibles.', { exact: false }).waitFor();
    console.log('Author UI without JS: permissions, nonce, create/replay, revisions, confirmed withdrawal while suspended, absent item, 503 exact retry, quota and closed module passed.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
