const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const launch = require('../../Ui/recipe/browser-engine.cjs');
const base = 'http://127.0.0.1:8768';
const creator = '11111111-1111-4111-8111-111111111111';
const output = process.env.FANS_UI_OUTPUT;
if (!output) throw new Error('FANS_UI_OUTPUT required');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await launch();
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort());
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const role = user => context.addCookies([{ name: 'fixture_user', value: String(user), url: base }]);
  const api = async (route, data) => {
    const r = await context.request.fetch(`${base}/wp-json/faluss-fans/v1/${route}`, { method: data ? 'POST' : 'GET', headers: { 'X-WP-Nonce': 'fixture-wp_rest' }, ...(data ? { data } : {}) });
    return { status: r.status(), data: await r.json() };
  };
  const capture = async name => {
    await page.evaluate(() => document.fonts.ready);
    await page.evaluate(() => { document.activeElement?.blur(); scrollTo(0, 0); });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'no horizontal overflow');
    await page.screenshot({ path: path.join(output, name + '.png'), fullPage: true });
  };
  const confirmed = () => page.getByText('Action confirmée par le serveur. L’état courant est affiché ci-dessous.').waitFor();
  const post = async name => Promise.all([page.waitForNavigation({ waitUntil: 'load' }), page.getByRole('button', { name, exact: true }).click()]);
  try {
    await role(17);
    const own = (await api('creators/me/editorial')).data;
    const edit = await api('creators/me/editorial', { revision: Number(own?.revision || 0), public_name: 'Atelier de recette · données synthétiques', bio: 'Présentation de test approuvée via le service réel. Aucun compte réel.', portrait_id: '', portrait_revision: 0 });
    assert.equal(edit.status, 200);
    await role(1); assert.equal((await api(`editorial/${creator}/moderate`, { revision: Number(edit.data.revision), decision: 'approve', reason: 'allowed_editorial' })).status, 200);
    await role(0); await page.goto(`${base}/faluss-fans/creators/${creator}`);
    await page.getByRole('link', { name: 'Adresser une demande de message' }).click();
    assert.equal(await page.getByRole('heading', { name: 'Connexion requise' }).count(), 1);
    assert.ok((await page.locator('input[name="faluss_fans_return_to"]').getAttribute('value'))?.includes('messages?creator='));
    await capture('guest-message-sso');
    await role(18); await page.goto(`${base}/faluss-fans/fan/messages?creator=${creator}`);
    await page.getByLabel('Votre demande textuelle').fill('Bonjour, ceci est une demande synthétique de recette. Peut-on échanger sur votre travail ?');
    await capture('fan-request-desktop');
    await post('Envoyer ma demande'); await confirmed();
    const thread = (await api('messages')).data.items[0].thread_id;
    await page.setViewportSize({ width: 390, height: 844 }); await capture('fan-pending-mobile');
    assert.equal(await page.getByRole('button', { name: 'Envoyer le message', exact: true }).count(), 0);
    await role(17); await page.goto(`${base}/faluss-fans/creator/messages?thread=${thread}`);
    assert.equal(await page.locator('.fu-nav__item').count(), 8);
    await capture('creator-request-mobile');
    await page.setViewportSize({ width: 1440, height: 1000 }); await capture('creator-request-desktop');
    await post('Accepter la demande'); await confirmed();
    await page.getByLabel('Votre message', { exact: true }).fill('Bonjour, votre demande de test est acceptée. Cette réponse passe par le formulaire et la base isolée.');
    await post('Envoyer le message'); await confirmed();
    await capture('creator-conversation-desktop');
    await page.setViewportSize({ width: 390, height: 844 }); await capture('creator-conversation-mobile');
    await role(18); await page.goto(`${base}/faluss-fans/fan/messages?thread=${thread}`);
    await page.getByLabel('Votre message', { exact: true }).fill('Merci. Ce troisième message vérifie l’échange bilatéral, sans donnée commerciale ni progression inventée.');
    await post('Envoyer le message'); await confirmed();
    await capture('fan-conversation-mobile');
    await page.setViewportSize({ width: 1440, height: 1000 }); await capture('fan-conversation-desktop');
    assert.doesNotMatch(await page.locator('.fu-messages').innerText(), /[0-9a-f]{8}-[0-9a-f]{4}-/);
    const received = page.locator('.fu-message-bubble:not(.is-mine)').first();
    await received.getByText('Signaler ce message', { exact: true }).click();
    await received.getByLabel('Motif du signalement').selectOption('other');
    await post('Confirmer le signalement'); await confirmed();
    const report = (await api('message-reports/mine')).data.items[0].case_id;
    await role(1); assert.equal((await page.goto(`${base}/admin.php?page=faluss-fans-moderation&view=messages&item=${report}`)).status(), 403);
    await role(42); const admin = `${base}/admin.php?page=faluss-fans-moderation&view=messages&item=${report}`;
    await page.goto(admin); await capture('moderation-proof-desktop');
    await page.setViewportSize({ width: 390, height: 844 }); await capture('moderation-proof-mobile');
    await page.getByLabel('Action après examen').selectOption('remove');
    await page.getByLabel('Motivation privée obligatoire').fill('Décision synthétique : retrait pour vérifier le parcours de recours.');
    await post('Confirmer l’action motivée');
    await page.getByText('Décision confirmée et journalisée.', { exact: true }).waitFor();
    await role(18); await page.goto(`${base}/faluss-fans/fan/messages?section=reports`);
    await page.getByLabel('Motiver un recours').fill('Recours synthétique transmis au modérateur depuis mon espace privé.');
    await post('Transmettre mon recours'); await confirmed(); await capture('fan-appeal-mobile');
    await role(42); await page.goto(admin);
    assert.equal(await page.locator('option[value="finalize"]').count(), 0);
    await page.getByLabel('Action après examen').selectOption('restore');
    await page.getByLabel('Motivation privée obligatoire').fill('Recours examiné dans cette recette ; restauration justifiée.');
    await post('Confirmer l’action motivée');
    await page.getByText('Décision confirmée et journalisée.', { exact: true }).waitFor();
    await page.getByLabel('Action après examen').selectOption('finalize');
    await page.getByLabel('Motivation privée obligatoire').fill('Décision de recette définitive, notifications et recours traités dans le scénario.');
    await page.getByRole('checkbox').check();
    await post('Confirmer l’action motivée');
    await page.getByText('Décision confirmée et journalisée.', { exact: true }).waitFor();
    await page.waitForLoadState('load');
    await page.evaluate(() => dispatchEvent(new PageTransitionEvent('pagehide')));
    assert.equal(await page.locator('[data-fans-private-proof]').innerText(), '');
    await role(18); await page.goto(`${base}/faluss-fans/fan/messages?thread=${thread}`);
    await post('Bloquer cet échange'); await confirmed();
    await capture('blocked-conversation-mobile');
    await role(17); assert.equal((await api(`messages/${thread}/send`, { body: 'Should be refused', key: crypto.randomUUID() })).status, 403);
    await role(18); await page.goto(`${base}/faluss-fans/fan/messages?section=blocks`);
    await post('Lever mon blocage'); await confirmed();
    await page.goto(`${base}/faluss-fans/fan/messages?thread=${thread}`);
    assert.equal(await page.getByLabel('Votre message', { exact: true }).count(), 1);
    await page.waitForLoadState('load');
    await page.evaluate(() => dispatchEvent(new PageTransitionEvent('pagehide')));
    assert.equal(await page.locator('[data-fans-private-reading]').innerText(), '');
    const native = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
    await native.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort());
    await native.addCookies([{ name: 'fixture_user', value: '18', url: base }]);
    const nojs = await native.newPage(); await nojs.goto(`${base}/faluss-fans/fan/messages?thread=${thread}`);
    await nojs.getByLabel('Votre message', { exact: true }).fill('Envoi réel depuis un navigateur sans JavaScript.');
    await Promise.all([nojs.waitForNavigation({ waitUntil: 'load' }), nojs.getByRole('button', { name: 'Envoyer le message', exact: true }).click()]);
    await nojs.getByText('Envoi réel depuis un navigateur sans JavaScript.', { exact: true }).waitFor();
    await native.close(); assert.deepEqual(errors, []);
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ browser: browser.version(), assertions: 'native request, guest SSO return, accept, bilateral send, report, dedicated moderation, appeal, finality, block, unblock, no-JS, no overflow, no visible UUID, pagehide privacy', scope: 'real PHP/HTTP/SQL; WordPress sessions are adapters; synthetic fixture only', screenshots: fs.readdirSync(output).filter(x => x.endsWith('.png')) }, null, 2));
    console.log('PASS browser messaging lifecycle and privacy');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
