<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/Profiles/recipe/bootstrap.php';
use Faluss\Platform\Fans\Messaging\ReportSchema;
use Faluss\Platform\Fans\Messaging\MessageService as Messages;
use Faluss\Platform\Fans\Messaging\MessageReading as Reading;
use Faluss\Platform\Fans\Messaging\MessageStore;
use Faluss\Platform\Fans\Messaging\MessageReports as Reports;
use Faluss\Platform\Fans\Messaging\ReportModeration as Review;
use Faluss\Platform\Fans\Messaging\ReportRetention;
function check(string $label,bool $ok): void {if(!$ok){throw new RuntimeException($label.' SQL='.$GLOBALS['wpdb']->last_error);}echo "PASS $label\n";}
function code(mixed $r): int {return $r instanceof WP_Error?(int)$r->data['status']:200;}
const CREATOR='11111111-1111-4111-8111-111111111111';
check('report schema explicit and idempotent',ReportSchema::installOrVerify()&&ReportSchema::installOrVerify());
$fixtureUser=18;$r=Messages::request(CREATOR,'Message signalé de test',wp_generate_uuid4());$thread=$r['thread_id'];$message=$r['message_id'];
check('self report refused',code(Reports::report($thread,$message,'spam'))===404);
$fixtureUser=17;$case=Reports::report($thread,$message,'spam');$id=$case['case_id'];
check('recipient reports pending request',code($case)===200);
check('report retries do not duplicate',Reports::report($thread,$message,'spam')['case_id']===$id);
check('ordinary retention unchanged by report',(int)$wpdb->get_var("SELECT revision FROM test_faluss_fans_dm_threads WHERE thread_id='$thread'")===1);
check('member status has no evidence',!str_contains(json_encode(Reports::own()),'Message signalé'));
foreach([0,17,18,1] as $fixtureUser) {check('evidence denied without dedicated capability '.$fixtureUser,code(Review::inspect($id))===403);}
$fixtureUser=42;$proof=Review::inspect($id);
check('authorized moderator reads minimal selected proof',$proof['body']==='Message signalé de test'&&$proof['reviewed_at']===null&&count($proof['events'])===1);
check('one isolated proof only',(int)$wpdb->get_var('SELECT COUNT(*) FROM test_faluss_fans_dm_reports')===1);
$wpdb->query("UPDATE test_faluss_fans_dm_reports SET review_due_at=UTC_TIMESTAMP()-INTERVAL 1 DAY WHERE case_id='$id'");
check('overdue review visible',Review::listing()['overdue']===1);
check('review recorded',code(Review::decide($id,1,'review','Réexamen motivé'))===200&&Review::listing()['overdue']===0);
$wpdb->query("CREATE TRIGGER fail_report_event BEFORE INSERT ON test_faluss_fans_dm_report_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='isolated report audit failure'");
check('audit failure rejects moderation',code(Review::decide($id,2,'remove','Motif de retrait'))===503);
$wpdb->query('DROP TRIGGER fail_report_event');
check('audit failure rolls back ordinary effect',$wpdb->get_var("SELECT body FROM test_faluss_fans_dm_messages WHERE message_id='$message'")==='Message signalé de test'&&(int)Review::inspect($id)['revision']===2);
check('remove hides ordinary text',code(Review::decide($id,2,'remove','Contenu retiré'))===200&&$wpdb->get_var("SELECT body FROM test_faluss_fans_dm_messages WHERE message_id='$message'")==='');
check('finality requires recourse attestation',code(Review::decide($id,3,'finalize','Non confirmé',false))===409);
$fixtureUser=18;check('subject can appeal',code(Reports::appeal($id,3,'Je conteste cette décision.'))===200);
check('duplicate appeal bounded per decision',code(Reports::appeal($id,4,'Encore'))===409);
$fixtureUser=42;check('pending appeal prevents finalization',code(Review::decide($id,4,'finalize','Pas terminé',true))===409);
check('appeal review can restore retained ordinary text',code(Review::decide($id,4,'restore','Recours examiné et retenu'))===200&&$wpdb->get_var("SELECT body FROM test_faluss_fans_dm_messages WHERE message_id='$message'")==='Message signalé de test');
check('moderator can restrict pending request',code(Review::decide($id,5,'restrict','Échange suspendu pendant examen'))===200);
$fixtureUser=17;check('restriction prevents acceptance',code(Messages::decide($thread,(int)Reading::conversation($thread)['revision'],'accept'))===403);
$fixtureUser=42;check('restoration preserves original pending state',code(Review::decide($id,6,'restore','Restriction levée'))===200&&$wpdb->get_var("SELECT state FROM test_faluss_fans_dm_threads WHERE thread_id='$thread'")==='pending');
check('ordinary purge independent of open report',$wpdb->query("UPDATE test_faluss_fans_dm_threads SET last_sent_at=UTC_TIMESTAMP()-INTERVAL 13 MONTH")===1&&MessageStore::purge()['purged']===1&&Review::inspect($id)['body']==='Message signalé de test');
check('restore never resurrects purged messages',code(Review::decide($id,7,'restore','Données ordinaires déjà expirées'))===200&&(int)$wpdb->get_var('SELECT COUNT(*) FROM test_faluss_fans_dm_messages')===0);
check('final decision starts evidence clock',code(Review::decide($id,8,'finalize','Recours examinés ; décision définitive attestée.',true))===200&&Review::inspect($id)['final_at']!==null);
check('ordinary operations cannot reopen final decision',code(Review::decide($id,9,'remove','Trop tard'))===409);
check('empty litigation motivation rejected',code(Review::decide($id,9,'hold','',false,30))===400);
check('unbounded litigation hold rejected',code(Review::decide($id,9,'hold','Litige',false,91))===400);
check('motivated litigation separately audited',code(Review::decide($id,9,'hold','Référence de litige de test ; preuve nécessaire.',false,30))===200&&count(Review::inspect($id)['holds'])===1);
$wpdb->query("UPDATE test_faluss_fans_dm_reports SET final_at=UTC_TIMESTAMP()-INTERVAL 12 MONTH WHERE case_id='$id'");
check('active litigation hold postpones only evidence purge',ReportRetention::purge()['purged']===0);
check('release hold is explicit',code(Review::decide($id,10,'release_hold','Litige terminé, justification archivée.'))===200);
check('expired proof is no longer delivered',code(Review::inspect($id))===410);
foreach(['reports','report_events','legal_holds'] as $table) {check('purged sensitive table '.$table,(int)$wpdb->get_var('SELECT COUNT(*) FROM test_faluss_fans_dm_'.$table)===0);}
check('evidence purge retry idempotent',ReportRetention::purge()['purged']===0);
$fixtureUser=18;$r=Messages::request(CREATOR,'First reported text',wp_generate_uuid4());$thread=$r['thread_id'];$first=$r['message_id'];
$fixtureUser=17;Messages::decide($thread,1,'accept');
$fixtureUser=18;$second=Messages::send($thread,'Second reported text',wp_generate_uuid4())['message_id'];
$fixtureUser=17;$a=Reports::report($thread,$first,'spam')['case_id'];$b=Reports::report($thread,$second,'spam')['case_id'];
$fixtureUser=42;Review::decide($a,1,'restrict','Restriction A');Review::decide($b,1,'restrict','Restriction B');
check('restoring one case does not lift another restriction',code(Review::decide($a,2,'restore','Recours A retenu'))===200&&$wpdb->get_var("SELECT state FROM test_faluss_fans_dm_threads WHERE thread_id='$thread'")==='paused_open');
check('last restriction can be lifted explicitly',code(Review::decide($b,2,'restore','Recours B retenu'))===200&&$wpdb->get_var("SELECT state FROM test_faluss_fans_dm_threads WHERE thread_id='$thread'")==='open');
Review::decide($a,3,'finalize','Recours A achevé',true);Review::decide($b,3,'finalize','Recours B achevé',true);
$wpdb->query('UPDATE test_faluss_fans_dm_reports SET final_at=UTC_TIMESTAMP()-INTERVAL 13 MONTH');
$wpdb->query("CREATE TRIGGER fail_evidence_purge BEFORE DELETE ON test_faluss_fans_dm_reports FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='isolated evidence purge failure'");
check('evidence purge failure explicit',code(ReportRetention::purge())===503);
$wpdb->query('DROP TRIGGER fail_evidence_purge');
check('evidence purge rollback preserves audit',(int)$wpdb->get_var('SELECT COUNT(*) FROM test_faluss_fans_dm_report_events')===8);
check('evidence purge retries completely',ReportRetention::purge()['purged']===2);
$wpdb->query('UPDATE test_faluss_fans_dm_threads SET last_sent_at=UTC_TIMESTAMP()-INTERVAL 13 MONTH');MessageStore::purge();
